### ISSUE TITLE
bash train_selfsup.sh error

### ISSUE THREAD

**Issue by russellgeum** [visinf/multi-mono-sf#3]
I cloned the code and even installed it.

When I run "bash train_selfsup.sh" in scripts, the following error appears:
"unrecognized arguments: where checkpoints and log files will be saved)/MonoSceneFlow_Multi-selfsup-20210722-135602 Raw dataset path) Raw dataset path)"
Is there any additional folder configuration I need to set up?

**Comment by hurjunhwa** [comment]
Hi,

I think the two PATHs in the script file have not been properly set.
Please open the script file and configure the two following paths properly.
Then it should work!
```
DATA_HOME
EXPERIMENTS_HOME
```
``DATA_HOME`` is the directory where you save the KITTI Raw dataset in your local machine.
``EXPERIMENTS_HOME`` is the directory where you want to save log files and checkpoints during training.

Please let me know if it still doesn't work!
